### ISSUE TITLE
read-datacenter configuration not working as expected

### ISSUE THREAD

**Issue by faizmsft** [Azure-Samples/azure-cosmos-cassandra-extensions-java-sample-v4#8]
As per the documentation in the reference.conf, the "read-datacenter" configuration if added would typically allow reads from the local region but that not happening in the older and recent version of the cassandra extension library

### Application configuration

_Library_ 
```
 <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-cosmos-cassandra-driver-4-extensions</artifactId>
            <version>1.1.2</version>
  </dependency>
```

_Extension related configuration in the code_ 
```
System.setProperty("datastax-java-driver.basic.load-balancing-policy.class",
                "com.azure.cosmos.cassandra.CosmosLoadBalancingPolicy");
System.setProperty("datastax-java-driver.basic.load-balancing-policy.global-endpoint","cassandraks.cassandra.cosmos.azure.com:10350");
System.setProperty("datastax-java-driver.basic.load-balancing-policy.write-datacenter","South India");
System.setProperty("datastax-java-driver.basic.load-balancing-policy.read-datacenter","West US");
```

_Cosmos Cassandra account is configured with 4 regions_ 

![image](https://user-images.githubusercontent.com/92173585/204461281-14481556-b7c4-4d3d-b526-12fbc4cbcfa1.png)

###  Code Execution

Based on the above configuration, we are expecting the reads to happen from the "West US" region for the following cassandra operation 

![image](https://user-images.githubusercontent.com/92173585/204461692-02b8a0a0-6695-49d9-ac40-38cac238b3ab.png)

What we noticed in the server side diagnostics was that the Execute operation happened in the "South India" region, following snap for reference. 

![image](https://user-images.githubusercontent.com/92173585/204460696-dfb86927-ea40-41d7-bb4d-a518294c4fe5.png)

When we perform the Query operation then also the same thing is observed, following snaps for reference 

![image](https://user-images.githubusercontent.com/92173585/204462127-ca11ee3b-8701-4252-b3aa-183ffaff6835.png)

Check the region, it is "South India" instead of "West US"

![image](https://user-images.githubusercontent.com/92173585/204463610-89c2b85e-cbe8-4566-9424-7fa0a63a4c88.png)

### Preferred region configuration 

If we perform the test now with the preferred region configuration, the first region is treated as the local or preferred region and the code get executed in that specific region. 

As per the following configuration, the "West US" is the read-datacenter location and "Southeast Asia" is the first region in the preferred locations configuration. 

![image](https://user-images.githubusercontent.com/92173585/204463056-f72f14bc-bc10-4726-8f82-5ce29438f5cb.png)

When we execute the Query operation, it gets executed in "Southeast Asia" region instead of "West US" region

![image](https://user-images.githubusercontent.com/92173585/204464520-28568403-d8c8-4946-b761-a3e52c072304.png)

### Need help/clarity
1. Why the read-datacenter property which means read from local region is not working as expected 
2. The preferred region configuration based on my understanding talking to few folks and the blog would be applicable during failover scenarios, so why is the first region treated as the local read region

**Comment by iriaosara** [comment]
https://learn.microsoft.com/en-us/azure/cosmos-db/cassandra/driver-extensions
